### PR TITLE
[WIP] Dockerise environment

### PR DESCRIPTION
**Pull request by jjok**
I think using Docker or similar(?) would at least help get people involved with development, and potentially also make distributing Mugsy images for Production a lot easier too.

@margyle Have you used Docker before?

### CODE REVIEW

**Comment by margyle** [comment]
I only know the very basics and haven't actually used it much. I have been hoping to learn more though and had thought it would be a great fit for the exact reasons you listed. Really appreciate this commit, definitely not something I would have been able to implement with out finding some extra time to learn the basics.

**Comment by jjok** [comment]
It means, to get Decaf running on a Pi, you have to:

1. Burn Raspbian to your SD card
2. Install Git and Docker
3. Clone this repo
4. Build the image
5. Run the image

That would be the process for development.

For Production, you would
1. Do the build yourself
2. Push it to some public(?) Docker image repository (eg Docker Hub)
3. Have some way, on each Musgy, to change to see if there's a new version of the image, and pull it, if there is.

**Comment by jjok** [comment]
@margyle Do you want me to add the commands to the README?

**Comment by margyle** [comment]
Thanks for the additional info! Feel free to add to the readme as well. I'm gonna find some time to organize/clean it up tomorrow.

**Pull request merged**
